### ISSUE TITLE
Loading the same graph twice within same scope using NetworkXGraphImporter does not reflect all the fields

### ISSUE THREAD

**Issue by kthare10** [fabric-testbed/InformationModel#100]
See for the Issue Details: https://github.com/fabric-testbed/ControlFramework/issues/167

Scenario:
- Load a graph (`graphId = X`) from a file into ExperimentTopology such as Nodes do not have `management_ip`
- Print Nodes and `management_ip` is None for each node
- Within the same program, Load a graph (`graphId = X`) from a file into ExperimentTopology such as Nodes do have `management_ip`
- Print Nodes and `management_ip is` None for each node but it should depict the value observed in the graph

Root Cause:
- Loading a graph in Experiment Topology uses `NetworkXGraphImporter` which has `NetworkXGraphStorage` object which is singleton class
- `NetworkXGraphStorage:: add_graph_direct` method does not add/update an already present graph. This causing the second load to not get the graph updated and hence returns old information.
```
    def import_graph_from_string_direct(self, *, graph_string: str) -> ABCPropertyGraph:
        """
        Load graph serialized as a GraphML string with no checks or manipulations. It is
        assumed the GraphML already contains graph ids and node ids.
        :param graph_string:
        :return:
        """
        assert graph_string is not None

        with tempfile.NamedTemporaryFile(suffix="-graphml", mode='w') as f1:
            f1.write(graph_string)
            f1.flush()
            # get graph id (kinda inefficient, because reads graph in, then discards)
            graph_id = self.get_graph_id(graph_file=f1.name)
            # read using networkx
            self.storage.add_graph_direct(graph_id=graph_id, graph=nx.read_graphml(f1.name))
```

Code Snippet to reproduce the problem:
```
def load(file_name: str):
    import fim.user as fu

    t = fu.ExperimentTopology()
    t.load(file_name=file_name)
    print(f"1st Topology Nodes------{t.graph_model.graph_id}")

    for node in t.nodes.values():
        print("Node:")
        print(f"   Site              : {node.site}")
        print(f"   Type              : {node.type}")
        print(f"   Management IP     : {node.management_ip}")
        print(f"   Capaciy Hints     : {node.capacity_hints}")
        print(f"   Location          : {node.location}")
        print(f"   Components        : {node.components}")
        print(f"   Interface         : {node.interfaces}")
        print(f"   Sliver            : {node.get_sliver()}")

        print()
    print("===========================")


def main():
    load(file_name="./before.graphml")
    load(file_name="./after.graphml")


if __name__ == '__main__':
    main()
```

Files used to reproduce the problem: `before.graphml` and `after.graphml` (Please rename them to exclude .txt extension)
[after.graphml.txt](https://github.com/fabric-testbed/InformationModel/files/8099187/after.graphml.txt)
[before.graphml.txt](https://github.com/fabric-testbed/InformationModel/files/8099189/before.graphml.txt)

**Comment by ibaldin** [comment]
Fixed in #101
