### ISSUE TITLE
Add AL2S network topology model with L3VPN and cloud connect service capabilities

### ISSUE THREAD

**Issue by xi-yang** [fabric-testbed/InformationModel#121]
Initial model: 
* [x] 1. A single node topology abstraction with all AL2S ports (endpoints) peering with FABRIC as well as with Cloud Providers (AWS / GCP, Azure)
* [ ] 2. Cloud facing FacilityPort (or StitchPort) with additional modeling of cloud provider specs, as well as L3 peering capabilities.
* [ ] 3. Modeling of L3 peering capabilities between FABRIC and AL2S ports, whatever meaningful for the Orchestrators to determine a BGP peering / termination.

**Comment by ibaldin** [comment]
Take a look at FABRIC Information Model design doc for inspiration and we can discuss.

**Comment by ibaldin** [comment]
@xi-yang working on this. Expect in fim-1.4.0b7

**Comment by ibaldin** [comment]
OK so 1.4.0rc0 I think has what you want. examples on #148

**Comment by ibaldin** [comment]
See fabric-testbed/InformationModel#151 and fabric-testbed/AMHandlers#74
