### ISSUE TITLE
Update README: virtualenvwrapper and/or venv

### ISSUE THREAD

**Issue by sajith** [fabric-testbed/InformationModel#144]
In README, under the section titled "development environment", we state that `virtualenv` is recommended.  But what we really assume there is that [virtualenvwrapper](https://pypi.org/project/virtualenvwrapper/) is installed (that is where `mkvirtualenv` and `workon` commands come from), not just [virtualenv](https://pypi.org/project/virtualenv/).

Installing and using virtualenvwrapper requires additional steps, and some knowledge of the tool.  This is fine.  However, Python 3 also ships a built-in [venv](https://docs.python.org/3/library/venv.html) module which seems to work just fine with FIM. We can use venv like so:

```
$ git clone git@github.com:fabric-testbed/InformationModel.git
$ cd InformationModel
$ python3 -m venv venv
$ source ./venv/bin/activate
$ pip install --upgrade pip setuptools
(venv) $ 
```

(Older versions of pip and setuptools that gets shipped with Python may not always work; which is why `pip install --upgrade pip setuptools` is a good idea.)

It would be useful to update the README.  We could:

 - Recommend one or both of virtualenvwrapper and venv.
 - Add a link to virtualenvwrapper PyPI project, if that is still recommended.
 - Add instructions for using `venv`, if using `venv` is acceptable.

**Comment by ibaldin** [comment]
Fixed by [fb125a3](https://github.com/fabric-testbed/InformationModel/commit/fb125a386c1fd5ee596978a37aea8102855226b0)
