### ISSUE TITLE
Add support for diff on Labels

### ISSUE THREAD

**Issue by kthare10** [fabric-testbed/InformationModel#174]
Add support for diff function to implemented for `Labels` just like `Capacities` without which sliver_diff  returns false positive/negative.

**Comment by ibaldin** [comment]
Labels do not have __eq__ implemented, which makes prop_diff() behave differently. Will add a method.

**Comment by ibaldin** [comment]
This fix was insufficient as diff methods of nodes and network services did not check if only labels or capacities have changed (without changing any attached elements). Addressed on
