### ISSUE TITLE
Revise flavor sizes 

### ISSUE THREAD

**Issue by ibaldin** [fabric-testbed/InformationModel#177]
- Revise flavor sizes to have >10G < 100G disks
- Also create flavors that have 1TB disks with 64 cores/384G RAM so two such VMs can be allocated on each worker (some workers don't have enough disk to create 2x2TB vDisks)

Probably best to add 'point' flavors - small number - to accommodate these. 

Also related to fabric-testbed/software-planning#103

**Comment by cscarp** [comment]
For promethues storage, fabric racks are currently keeping 60 days of data which takes around 16GB for most racks (3workers) & up to 26GB(6?workers) for the bigger racks. So depending on the size of a slice, 32GB should give about a month's worth of data on 12 nodes.  Or a week worth of data on 48 nodes.

**Comment by ywsong2** [comment]
For ELK slice that has 3 worker nodes sending filebeat, metricbeat, packetbeat data, 4GB storage is required per day. 

Per 1 worker node that sends all 3 beats data to the measurement node, it requires 1.33GB storage per day or 40GB per month.  Users may need to turn off beats if they need to spin up large number of worker nodes.

For CPU, the measurement node should have at least 4 cores and 16 GB RAM.

**Comment by jgriffioen** [comment]
Please add the following images configs to FABRIC for educational use:

Core, RAM, Disk

1, 4, 10
1, 8, 10
1, 16, 10

1, 8, 50 (If needed, this could be 32 or 40 instead)
1, 16, 50 (If needed, this could be 32 or 40 instead)
1, 32, 50 (If needed, this could be 32 or 40 instead)

**Comment by ibaldin** [comment]
This is addressed in #194
