### ISSUE TITLE
Labels - add support to save ethernet interface name

### ISSUE THREAD

**Issue by kthare10** [fabric-testbed/InformationModel#179]
Labels - add support to save ethernet interface name.

Currently, fablib determines the interface name using the mac address for an interface. Since, AM already executes a task to determine the PCI address, same task has been extended to grab the ethernet interface name as well.

This will help avoid extra SSH calls via fablib as this information would be available in Fim model.
Currently there is no place to store the ethernet interface name in Labels. Hence the request.

**Comment by ibaldin** [comment]
I can easily accommodate this today as part of https://github.com/fabric-testbed/InformationModel/pull/175 if you prefer. It will be a new 1.4.x release

**Comment by ibaldin** [comment]
the `local_name` field already provides the required capability, so no need to do anything.
