### ISSUE TITLE
Multiple FabNetExt services for the same site do not trigger a validation error

### ISSUE THREAD

**Issue by kthare10** [fabric-testbed/InformationModel#187]
Create a slice with 2 VMs
Add 2 FabNetv4Ext services at the same site
Slice can be created despite the validation rule of allowing one FabNet service per site

**Comment by ibaldin** [comment]
- In ASM we expect a single L3 service (FABNetv4[Ext] or FABNetv6[Ext]) per site. These services connect interfaces of the nodes within the site in ASM.
- In ARMs there is a FABNetv4[Ext] or FABNetv6[Ext] attached to each site switch. 
- Current validation rules have no limit on the number of instances.

**Comment by ibaldin** [comment]
Fixed by 8d4b095 on #194

**Comment by ibaldin** [comment]
Modified the structure of validation for network services to include a section that modifies network services in the entire model (thus e.g. counting how many instances of a particular service type per site there are).
