### ISSUE TITLE
Install issues with Python versions 3.7 and 3.9

### ISSUE THREAD

**Issue by xi-yang** [fabric-testbed/InformationModel#3]
* The latest Mac OS X has python version >= 3.9.
Running `mkvirtualenv -r requirements.txt infomodel `, I am getting “Building wheel for recordclass (setup.py) ... error”. This can be reproduced by `pip3.9 install recordclass==0.14.0`. 

   `pip3.8 install recordclass==0.14.0` instead will install correctly. 

* CentOS 8.2 has python version 3.6.8. I manually installed 3.7, which however failed to install the InformationModel packages. 

* Python version 3.8 works fine for me on Mac OS X. I used pyenv instead of mkvirtualenv. The procedure is as follows.
```
brew install pyenv
pyenv install 3.8.6
pyenv init
eval "$(pyenv init -)"
pyenv shell 3.8.6
pip install -r requirements.txt
pip install -e .
pip install fabric-fim
```

I did not try 3.7 on Mac OS X. According to @ibaldin, it should also work.

**Comment by ibaldin** [comment]
Please let me know if there are still problems with versions >= 0.26

**Comment by ibaldin** [comment]
Seems this is not a problem anymore, especially when using venvs.
