### ISSUE TITLE
Component Name dictionaries (possibly non-issue)

### ISSUE THREAD

**Issue by ninjajoe9** [fabric-testbed/InformationModel#52]
While playing with the adding components to a node I discovered (unsurprisingly) you had to match the name of the component exactly. It took me an embarrassingly long time to figure out 'Tesla_T4' and 'TeslaT4' could not be substituted for 'Tesla T4'. Perhaps in one of the user guides include a note that spaces are fine when assigning components. 
<img width="713" alt="Screen Shot 2021-05-28 at 13 19 18" src="https://user-images.githubusercontent.com/48168373/120020703-13ae2680-bfb8-11eb-8b6b-74876a4ee333.png">

**Comment by ibaldin** [comment]
Topology validation will be taken care of in #57 . Other portions of this ticket have, I think, been addressed.
